/* generated vector source file - do not edit */
        #include "bsp_api.h"
        /* Do not build these data structures if no interrupts are currently allocated because IAR will have build errors. */
        void ssi_rxi_isr(void);
void ssi_int_isr(void);
#if VECTOR_DATA_IRQ_COUNT > 0
        BSP_DONT_REMOVE const fsp_vector_t g_vector_table[BSP_ICU_VECTOR_NUM_ENTRIES] BSP_PLACE_IN_SECTION(BSP_SECTION_APPLICATION_VECTORS) =
        {
                        [0] = layer3_switch_gwdi_isr, /* ETHER GWDI0 (GWCA Data Interrupt 0) */
            [1] = layer3_switch_eaei_isr, /* ETHER EAEI0 (ETHA0 Error Interrupt) */
            [2] = layer3_switch_eaei_isr, /* ETHER EAEI1 (ETHA1 Error Interrupt) */
            [3] = sci_b_uart_rxi_isr, /* SCI2 RXI (Receive data full) */
            [4] = sci_b_uart_txi_isr, /* SCI2 TXI (Transmit data empty) */
            [5] = sci_b_uart_tei_isr, /* SCI2 TEI (Transmit end) */
            [6] = sci_b_uart_eri_isr, /* SCI2 ERI (Receive error) */
            [7] = iic_master_rxi_isr, /* IIC0 RXI (Receive data full) */
            [8] = iic_master_txi_isr, /* IIC0 TXI (Transmit data empty) */
            [9] = iic_master_tei_isr, /* IIC0 TEI (Transmit end) */
            [10] = iic_master_eri_isr, /* IIC0 ERI (Transfer error) */
            [11] = drw_int_isr, /* DRW INT (DRW interrupt) */
            [12] = sdhimmc_accs_isr, /* SDHIMMC0 ACCS (Card access) */
            [13] = sdhimmc_card_isr, /* SDHIMMC0 CARD (Card detect) */
            [14] = dmac_int_isr, /* DMAC0 INT (DMAC0 transfer end) */
            [15] = ssi_txi_isr, /* SSI0 TXI (Transmit data empty) */
            [16] = ssi_int_isr, /* SSI0 INT (Error interrupt) */
            [17] = usbfs_interrupt_handler, /* USBFS INT (USBFS interrupt) */
            [18] = usbfs_resume_handler, /* USBFS RESUME (USBFS resume interrupt) */
            [19] = usbfs_d0fifo_handler, /* USBFS FIFO 0 (DMA/DTC transfer request 0) */
            [20] = usbfs_d1fifo_handler, /* USBFS FIFO 1 (DMA/DTC transfer request 1) */
            [21] = usbhs_interrupt_handler, /* USBHS USB INT RESUME (USBHS interrupt) */
            [22] = usbhs_d0fifo_handler, /* USBHS FIFO 0 (DMA transfer request 0) */
            [23] = usbhs_d1fifo_handler, /* USBHS FIFO 1 (DMA transfer request 1) */
            [24] = adc_b_limclpi_isr, /* ADC LIMCLPI (Limiter clip interrupt with the limit table 0 to 7) */
            [25] = adc_b_err0_isr, /* ADC ERR0 (A/D converter unit 0 Error) */
            [26] = adc_b_err1_isr, /* ADC ERR1 (A/D converter unit 1 Error) */
            [27] = adc_b_resovf0_isr, /* ADC RESOVF0 (A/D conversion overflow on A/D converter unit 0) */
            [28] = adc_b_resovf1_isr, /* ADC RESOVF1 (A/D conversion overflow on A/D converter unit 1) */
            [29] = adc_b_calend0_isr, /* ADC CALEND0 (End of calibration of A/D converter unit 0) */
            [30] = adc_b_calend1_isr, /* ADC CALEND1 (End of calibration of A/D converter unit 1) */
            [31] = adc_b_adi0_isr, /* ADC ADI0 (End of A/D scanning operation(Gr.0)) */
            [32] = adc_b_adi1_isr, /* ADC ADI1 (End of A/D scanning operation(Gr.1)) */
            [33] = adc_b_adi2_isr, /* ADC ADI2 (End of A/D scanning operation(Gr.2)) */
            [34] = adc_b_adi3_isr, /* ADC ADI3 (End of A/D scanning operation(Gr.3)) */
            [35] = adc_b_adi4_isr, /* ADC ADI4 (End of A/D scanning operation(Gr.4)) */
            [36] = adc_b_fifoovf_isr, /* ADC FIFOOVF (FIFO data overflow) */
            [37] = adc_b_fiforeq0_isr, /* ADC FIFOREQ0 (FIFO data read request interrupt(Gr.0)) */
            [38] = adc_b_fiforeq1_isr, /* ADC FIFOREQ1 (FIFO data read request interrupt(Gr.1)) */
            [39] = adc_b_fiforeq2_isr, /* ADC FIFOREQ2 (FIFO data read request interrupt(Gr.2)) */
            [40] = adc_b_fiforeq3_isr, /* ADC FIFOREQ3 (FIFO data read request interrupt(Gr.3)) */
            [41] = adc_b_fiforeq4_isr, /* ADC FIFOREQ4 (FIFO data read request interrupt(Gr.4)) */
            [42] = canfd_error_isr, /* CAN0 CHERR (Channel  error) */
            [43] = canfd_channel_tx_isr, /* CAN0 TX (Transmit interrupt) */
            [44] = canfd_common_fifo_rx_isr, /* CAN0 COMFRX (Common FIFO receive interrupt) */
            [45] = canfd_error_isr, /* CAN GLERR (Global error) */
            [46] = canfd_rx_fifo_isr, /* CAN RXF (Global receive FIFO interrupt) */
            [47] = gpt_counter_overflow_isr, /* GPT1 COUNTER OVERFLOW (Overflow) */
            [48] = rtc_alarm_periodic_isr, /* RTC ALARM (Alarm interrupt) */
            [49] = rtc_alarm_periodic_isr, /* RTC PERIOD (Periodic interrupt) */
            [50] = rtc_carry_isr, /* RTC CARRY (Carry interrupt) */
            [51] = r_icu_isr, /* ICU IRQ4 (External pin interrupt 4) */
            [52] = spi_b_rxi_isr, /* SPI1 RXI (Receive buffer full) */
            [53] = spi_b_txi_isr, /* SPI1 TXI (Transmit buffer empty) */
            [54] = spi_b_tei_isr, /* SPI1 TEI (Transmission complete event) */
            [55] = spi_b_eri_isr, /* SPI1 ERI (Error) */
            [56] = sci_b_uart_rxi_isr, /* SCI1 RXI (Receive data full) */
            [57] = sci_b_uart_txi_isr, /* SCI1 TXI (Transmit data empty) */
            [58] = sci_b_uart_tei_isr, /* SCI1 TEI (Transmit end) */
            [59] = sci_b_uart_eri_isr, /* SCI1 ERI (Receive error) */
            [60] = pdm_sdet_isr, /* PDM SDET (Sound detection interrupt) */
            [61] = pdm_dat_isr, /* PDM DAT2 (Data reception interrupt channel 2) */
            [62] = pdm_err_isr, /* PDM ERR2 (Error detection interrupt channel 2) */
            [63] = gpt_counter_overflow_isr, /* GPT0 COUNTER OVERFLOW (Overflow) */
            [64] = glcdc_line_detect_isr, /* GLCDC LINE DETECT (Specified line) */
            [65] = vin_status_isr, /* VIN IRQ (Interrupt Request) */
            [66] = vin_error_isr, /* VIN ERR (Interrupt Request for SYNC Error) */
            [67] = mipi_csi_rx_isr, /* MIPICSI RX (Receive interrupt) */
            [68] = mipi_csi_dl_isr, /* MIPICSI DL (Data Lane interrupt) */
            [69] = mipi_csi_vc_isr, /* MIPICSI VC (Virtual Channel interrupt) */
            [70] = mipi_csi_pm_isr, /* MIPICSI PM (Power Management interrupt) */
            [71] = mipi_csi_gst_isr, /* MIPICSI GST (Generic Short Packet interrupt) */
            [72] = rm_ethosu_isr, /* NPU IRQ (NPU IRQ) */
            [73] = ipc_isr, /* IPC IRQ1 (CPU Mutual Interrupt 1) */
            [74] = dmac_int_isr, /* DMAC1 INT (DMAC1 transfer end) */
            [75] = pdm_err_isr, /* PDM ERR0 (Error detection interrupt channel 0) */
            [76] = ssi_rxi_isr, /* SSI1 RXI (Receive data full) */
            [77] = ssi_int_isr, /* SSI1 INT (Error interrupt) */
        };
        #if BSP_FEATURE_ICU_HAS_IELSR
        const bsp_interrupt_event_t g_interrupt_event_link_select[BSP_ICU_VECTOR_NUM_ENTRIES] =
        {
            [0] = BSP_PRV_VECT_ENUM(EVENT_ETHER_GWDI0,GROUP0), /* ETHER GWDI0 (GWCA Data Interrupt 0) */
            [1] = BSP_PRV_VECT_ENUM(EVENT_ETHER_EAEI0,GROUP1), /* ETHER EAEI0 (ETHA0 Error Interrupt) */
            [2] = BSP_PRV_VECT_ENUM(EVENT_ETHER_EAEI1,GROUP2), /* ETHER EAEI1 (ETHA1 Error Interrupt) */
            [3] = BSP_PRV_VECT_ENUM(EVENT_SCI2_RXI,GROUP3), /* SCI2 RXI (Receive data full) */
            [4] = BSP_PRV_VECT_ENUM(EVENT_SCI2_TXI,GROUP4), /* SCI2 TXI (Transmit data empty) */
            [5] = BSP_PRV_VECT_ENUM(EVENT_SCI2_TEI,GROUP5), /* SCI2 TEI (Transmit end) */
            [6] = BSP_PRV_VECT_ENUM(EVENT_SCI2_ERI,GROUP6), /* SCI2 ERI (Receive error) */
            [7] = BSP_PRV_VECT_ENUM(EVENT_IIC0_RXI,GROUP7), /* IIC0 RXI (Receive data full) */
            [8] = BSP_PRV_VECT_ENUM(EVENT_IIC0_TXI,GROUP0), /* IIC0 TXI (Transmit data empty) */
            [9] = BSP_PRV_VECT_ENUM(EVENT_IIC0_TEI,GROUP1), /* IIC0 TEI (Transmit end) */
            [10] = BSP_PRV_VECT_ENUM(EVENT_IIC0_ERI,GROUP2), /* IIC0 ERI (Transfer error) */
            [11] = BSP_PRV_VECT_ENUM(EVENT_DRW_INT,GROUP3), /* DRW INT (DRW interrupt) */
            [12] = BSP_PRV_VECT_ENUM(EVENT_SDHIMMC0_ACCS,GROUP4), /* SDHIMMC0 ACCS (Card access) */
            [13] = BSP_PRV_VECT_ENUM(EVENT_SDHIMMC0_CARD,GROUP5), /* SDHIMMC0 CARD (Card detect) */
            [14] = BSP_PRV_VECT_ENUM(EVENT_DMAC0_INT,GROUP6), /* DMAC0 INT (DMAC0 transfer end) */
            [15] = BSP_PRV_VECT_ENUM(EVENT_SSI0_TXI,GROUP7), /* SSI0 TXI (Transmit data empty) */
            [16] = BSP_PRV_VECT_ENUM(EVENT_SSI0_INT,GROUP0), /* SSI0 INT (Error interrupt) */
            [17] = BSP_PRV_VECT_ENUM(EVENT_USBFS_INT,GROUP1), /* USBFS INT (USBFS interrupt) */
            [18] = BSP_PRV_VECT_ENUM(EVENT_USBFS_RESUME,GROUP2), /* USBFS RESUME (USBFS resume interrupt) */
            [19] = BSP_PRV_VECT_ENUM(EVENT_USBFS_FIFO_0,GROUP3), /* USBFS FIFO 0 (DMA/DTC transfer request 0) */
            [20] = BSP_PRV_VECT_ENUM(EVENT_USBFS_FIFO_1,GROUP4), /* USBFS FIFO 1 (DMA/DTC transfer request 1) */
            [21] = BSP_PRV_VECT_ENUM(EVENT_USBHS_USB_INT_RESUME,GROUP5), /* USBHS USB INT RESUME (USBHS interrupt) */
            [22] = BSP_PRV_VECT_ENUM(EVENT_USBHS_FIFO_0,GROUP6), /* USBHS FIFO 0 (DMA transfer request 0) */
            [23] = BSP_PRV_VECT_ENUM(EVENT_USBHS_FIFO_1,GROUP7), /* USBHS FIFO 1 (DMA transfer request 1) */
            [24] = BSP_PRV_VECT_ENUM(EVENT_ADC_LIMCLPI,GROUP0), /* ADC LIMCLPI (Limiter clip interrupt with the limit table 0 to 7) */
            [25] = BSP_PRV_VECT_ENUM(EVENT_ADC_ERR0,GROUP1), /* ADC ERR0 (A/D converter unit 0 Error) */
            [26] = BSP_PRV_VECT_ENUM(EVENT_ADC_ERR1,GROUP2), /* ADC ERR1 (A/D converter unit 1 Error) */
            [27] = BSP_PRV_VECT_ENUM(EVENT_ADC_RESOVF0,GROUP3), /* ADC RESOVF0 (A/D conversion overflow on A/D converter unit 0) */
            [28] = BSP_PRV_VECT_ENUM(EVENT_ADC_RESOVF1,GROUP4), /* ADC RESOVF1 (A/D conversion overflow on A/D converter unit 1) */
            [29] = BSP_PRV_VECT_ENUM(EVENT_ADC_CALEND0,GROUP5), /* ADC CALEND0 (End of calibration of A/D converter unit 0) */
            [30] = BSP_PRV_VECT_ENUM(EVENT_ADC_CALEND1,GROUP6), /* ADC CALEND1 (End of calibration of A/D converter unit 1) */
            [31] = BSP_PRV_VECT_ENUM(EVENT_ADC_ADI0,GROUP7), /* ADC ADI0 (End of A/D scanning operation(Gr.0)) */
            [32] = BSP_PRV_VECT_ENUM(EVENT_ADC_ADI1,FIXED), /* ADC ADI1 (End of A/D scanning operation(Gr.1)) */
            [33] = BSP_PRV_VECT_ENUM(EVENT_ADC_ADI2,FIXED), /* ADC ADI2 (End of A/D scanning operation(Gr.2)) */
            [34] = BSP_PRV_VECT_ENUM(EVENT_ADC_ADI3,FIXED), /* ADC ADI3 (End of A/D scanning operation(Gr.3)) */
            [35] = BSP_PRV_VECT_ENUM(EVENT_ADC_ADI4,FIXED), /* ADC ADI4 (End of A/D scanning operation(Gr.4)) */
            [36] = BSP_PRV_VECT_ENUM(EVENT_ADC_FIFOOVF,FIXED), /* ADC FIFOOVF (FIFO data overflow) */
            [37] = BSP_PRV_VECT_ENUM(EVENT_ADC_FIFOREQ0,FIXED), /* ADC FIFOREQ0 (FIFO data read request interrupt(Gr.0)) */
            [38] = BSP_PRV_VECT_ENUM(EVENT_ADC_FIFOREQ1,FIXED), /* ADC FIFOREQ1 (FIFO data read request interrupt(Gr.1)) */
            [39] = BSP_PRV_VECT_ENUM(EVENT_ADC_FIFOREQ2,FIXED), /* ADC FIFOREQ2 (FIFO data read request interrupt(Gr.2)) */
            [40] = BSP_PRV_VECT_ENUM(EVENT_ADC_FIFOREQ3,FIXED), /* ADC FIFOREQ3 (FIFO data read request interrupt(Gr.3)) */
            [41] = BSP_PRV_VECT_ENUM(EVENT_ADC_FIFOREQ4,FIXED), /* ADC FIFOREQ4 (FIFO data read request interrupt(Gr.4)) */
            [42] = BSP_PRV_VECT_ENUM(EVENT_CAN0_CHERR,FIXED), /* CAN0 CHERR (Channel  error) */
            [43] = BSP_PRV_VECT_ENUM(EVENT_CAN0_TX,FIXED), /* CAN0 TX (Transmit interrupt) */
            [44] = BSP_PRV_VECT_ENUM(EVENT_CAN0_COMFRX,FIXED), /* CAN0 COMFRX (Common FIFO receive interrupt) */
            [45] = BSP_PRV_VECT_ENUM(EVENT_CAN_GLERR,FIXED), /* CAN GLERR (Global error) */
            [46] = BSP_PRV_VECT_ENUM(EVENT_CAN_RXF,FIXED), /* CAN RXF (Global receive FIFO interrupt) */
            [47] = BSP_PRV_VECT_ENUM(EVENT_GPT1_COUNTER_OVERFLOW,FIXED), /* GPT1 COUNTER OVERFLOW (Overflow) */
            [48] = BSP_PRV_VECT_ENUM(EVENT_RTC_ALARM,FIXED), /* RTC ALARM (Alarm interrupt) */
            [49] = BSP_PRV_VECT_ENUM(EVENT_RTC_PERIOD,FIXED), /* RTC PERIOD (Periodic interrupt) */
            [50] = BSP_PRV_VECT_ENUM(EVENT_RTC_CARRY,FIXED), /* RTC CARRY (Carry interrupt) */
            [51] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ4,FIXED), /* ICU IRQ4 (External pin interrupt 4) */
            [52] = BSP_PRV_VECT_ENUM(EVENT_SPI1_RXI,FIXED), /* SPI1 RXI (Receive buffer full) */
            [53] = BSP_PRV_VECT_ENUM(EVENT_SPI1_TXI,FIXED), /* SPI1 TXI (Transmit buffer empty) */
            [54] = BSP_PRV_VECT_ENUM(EVENT_SPI1_TEI,FIXED), /* SPI1 TEI (Transmission complete event) */
            [55] = BSP_PRV_VECT_ENUM(EVENT_SPI1_ERI,FIXED), /* SPI1 ERI (Error) */
            [56] = BSP_PRV_VECT_ENUM(EVENT_SCI1_RXI,FIXED), /* SCI1 RXI (Receive data full) */
            [57] = BSP_PRV_VECT_ENUM(EVENT_SCI1_TXI,FIXED), /* SCI1 TXI (Transmit data empty) */
            [58] = BSP_PRV_VECT_ENUM(EVENT_SCI1_TEI,FIXED), /* SCI1 TEI (Transmit end) */
            [59] = BSP_PRV_VECT_ENUM(EVENT_SCI1_ERI,FIXED), /* SCI1 ERI (Receive error) */
            [60] = BSP_PRV_VECT_ENUM(EVENT_PDM_SDET,FIXED), /* PDM SDET (Sound detection interrupt) */
            [61] = BSP_PRV_VECT_ENUM(EVENT_PDM_DAT2,FIXED), /* PDM DAT2 (Data reception interrupt channel 2) */
            [62] = BSP_PRV_VECT_ENUM(EVENT_PDM_ERR2,FIXED), /* PDM ERR2 (Error detection interrupt channel 2) */
            [63] = BSP_PRV_VECT_ENUM(EVENT_GPT0_COUNTER_OVERFLOW,FIXED), /* GPT0 COUNTER OVERFLOW (Overflow) */
            [64] = BSP_PRV_VECT_ENUM(EVENT_GLCDC_LINE_DETECT,FIXED), /* GLCDC LINE DETECT (Specified line) */
            [65] = BSP_PRV_VECT_ENUM(EVENT_VIN_IRQ,FIXED), /* VIN IRQ (Interrupt Request) */
            [66] = BSP_PRV_VECT_ENUM(EVENT_VIN_ERR,FIXED), /* VIN ERR (Interrupt Request for SYNC Error) */
            [67] = BSP_PRV_VECT_ENUM(EVENT_MIPICSI_RX,FIXED), /* MIPICSI RX (Receive interrupt) */
            [68] = BSP_PRV_VECT_ENUM(EVENT_MIPICSI_DL,FIXED), /* MIPICSI DL (Data Lane interrupt) */
            [69] = BSP_PRV_VECT_ENUM(EVENT_MIPICSI_VC,FIXED), /* MIPICSI VC (Virtual Channel interrupt) */
            [70] = BSP_PRV_VECT_ENUM(EVENT_MIPICSI_PM,FIXED), /* MIPICSI PM (Power Management interrupt) */
            [71] = BSP_PRV_VECT_ENUM(EVENT_MIPICSI_GST,FIXED), /* MIPICSI GST (Generic Short Packet interrupt) */
            [72] = BSP_PRV_VECT_ENUM(EVENT_NPU_IRQ,FIXED), /* NPU IRQ (NPU IRQ) */
            [73] = BSP_PRV_VECT_ENUM(EVENT_IPC_IRQ1,FIXED), /* IPC IRQ1 (CPU Mutual Interrupt 1) */
            [74] = BSP_PRV_VECT_ENUM(EVENT_DMAC1_INT,FIXED), /* DMAC1 INT (DMAC1 transfer end) */
            [75] = BSP_PRV_VECT_ENUM(EVENT_PDM_ERR0,FIXED), /* PDM ERR0 (Error detection interrupt channel 0) */
            [76] = BSP_PRV_VECT_ENUM(EVENT_SSI1_RXI,FIXED), /* SSI1 RXI (Receive data full) */
            [77] = BSP_PRV_VECT_ENUM(EVENT_SSI1_INT,FIXED), /* SSI1 INT (Error interrupt) */
        };
        #endif
        #endif