#pragma once

/* Titan Mini HW V1.0 onboard pair. Not IM69D130. Acoustic proof is still required. */
#define K1_TITAN_ONBOARD_MIC_MPN "LMD2718T261-OA1"
#define K1_TITAN_ONBOARD_MIC_DATA_PIN "P502"
#define K1_TITAN_ONBOARD_MIC_CLOCK_PIN "P812"
#define K1_TITAN_ONBOARD_MIC_DATA_AF "PDMDAT2"
#define K1_TITAN_ONBOARD_MIC_CLOCK_AF "PDMCLK2"

#define K1_TITAN_ONBOARD_U13_SELECT "HIGH"
#define K1_TITAN_ONBOARD_U13_EDGE "FALL"
#define K1_TITAN_ONBOARD_U13_CHANNEL 0u
#define K1_TITAN_ONBOARD_U13_ROLE "measurement"

#define K1_TITAN_ONBOARD_U14_SELECT "LOW"
#define K1_TITAN_ONBOARD_U14_EDGE "RISE"
#define K1_TITAN_ONBOARD_U14_CHANNEL 2u
#define K1_TITAN_ONBOARD_U14_ROLE "programme"
